server:
  port: 9091
  error:
    include-message: always

spring:
  application:
    name: client-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:clientDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    plataform: h2
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-plataform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

